# Generated by Django 5.1.3 on 2024-11-24 08:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='created_at',
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='office_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
